const std = @import("std");
const palette = @import("palette.zig");

pub fn render(allocator: std.mem.Allocator, variant: palette.Variant) ![]u8 {
    var output: std.Io.Writer.Allocating = .init(allocator);
    errdefer output.deinit();
    const writer = &output.writer;
    const p = variant.palette;

    try writer.writeAll("# Generated by dark-fire. Do not edit directly.\n");
    try writer.writeByte('\n');

    const ansi = [_]palette.Color{
        p.surface(-2),  p.red(-1),    p.green(-1), p.yellow(-1),
        p.blue(-1),     p.purple(-1), p.cyan(-1),  p.fg(),
        p.greyscale(5), p.red(1),     p.green(1),  p.yellow(1),
        p.blue(1),      p.purple(1),  p.cyan(1),   p.brightFg(),
    };
    for (ansi, 0..) |color, index| {
        try writer.print("palette = {d}=", .{index});
        try writeColor(writer, color);
        try writer.writeByte('\n');
    }

    try writer.writeAll("background = ");
    try writeColor(writer, p.background());
    try writer.writeAll("\nforeground = ");
    try writeColor(writer, p.fg());
    try writer.writeAll("\ncursor-color = ");
    try writeColor(writer, p.brightFg());
    try writer.writeAll("\ncursor-text = ");
    try writeColor(writer, p.background());
    try writer.writeAll("\nselection-background = ");
    try writeColor(writer, p.greyscale(3));
    try writer.writeAll("\nselection-foreground = ");
    try writeColor(writer, p.fg());
    try writer.writeByte('\n');

    return output.toOwnedSlice();
}

fn writeColor(writer: *std.Io.Writer, color: palette.Color) !void {
    const hex = "0123456789ABCDEF";
    try writer.writeByte('#');
    inline for (.{ color.r, color.g, color.b }) |byte| {
        try writer.writeByte(hex[byte >> 4]);
        try writer.writeByte(hex[byte & 0x0f]);
    }
}

test "Ghostty output contains all ANSI colors and full black" {
    const allocator = std.testing.allocator;
    const output = try render(allocator, palette.findVariant("full-black").?);
    defer allocator.free(output);
    try std.testing.expectEqual(@as(usize, 16), std.mem.count(u8, output, "palette = "));
    try std.testing.expect(std.mem.indexOf(u8, output, "background = #000000") != null);
}
