const std = @import("std");
const palette = @import("palette.zig");

pub fn render(allocator: std.mem.Allocator, variants: []const palette.Variant) ![]u8 {
    var output: std.Io.Writer.Allocating = .init(allocator);
    errdefer output.deinit();
    const writer = &output.writer;

    try writer.writeAll("/* Generated by pale-fire. Do not edit directly. */\n\n");

    for (variants, 0..) |variant, index| {
        if (index != 0) try writer.writeByte('\n');
        try writer.print("/* {s} */\n[data-pale-fire-theme=\"{s}\"] {{\n", .{ variant.label, variant.slug });
        try writePalette(writer, variant.palette);
        try writer.writeAll("}\n");
    }

    return output.toOwnedSlice();
}

fn writePalette(writer: *std.Io.Writer, p: palette.Palette) !void {
    try writeVariable(writer, "background", p.background());
    try writeVariable(writer, "surface", p.surface(-1));
    try writeVariable(writer, "surface-raised", p.surface(1));
    try writeVariable(writer, "border", p.greyscale(3));
    try writeVariable(writer, "foreground", p.fg());
    try writeVariable(writer, "muted", p.greyscale(5));
    try writeVariable(writer, "accent", p.blue(0));
    try writeVariable(writer, "selection", p.greyscale(3));
    try writeVariable(writer, "keyword", p.keywords());
    try writeVariable(writer, "string", p.red(-1));
    try writeVariable(writer, "number", p.green(1));
    try writeVariable(writer, "comment", p.green(-2));
    try writeVariable(writer, "function", p.functions());
    try writeVariable(writer, "type", p.types());
    try writeVariable(writer, "property", p.properties());
    try writeVariable(writer, "constant", p.constants());
}

fn writeVariable(writer: *std.Io.Writer, name: []const u8, color: palette.Color) !void {
    const hex = "0123456789ABCDEF";
    try writer.print("  --pf-{s}: #", .{name});
    inline for (.{ color.r, color.g, color.b }) |byte| {
        try writer.writeByte(hex[byte >> 4]);
        try writer.writeByte(hex[byte & 0x0f]);
    }
    try writer.writeAll(";\n");
}

test "web output contains every variant and semantic token colors" {
    const allocator = std.testing.allocator;
    const output = try render(allocator, &palette.variants);
    defer allocator.free(output);

    try std.testing.expectEqual(@as(usize, palette.variants.len), std.mem.count(u8, output, "[data-pale-fire-theme="));
    try std.testing.expect(std.mem.indexOf(u8, output, "[data-pale-fire-theme=\"original\"]") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "--pf-background: #404040;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "--pf-keyword: #") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "[data-pale-fire-theme=\"full-black\"]") != null);
    try std.testing.expect(std.mem.indexOfPos(u8, output, std.mem.indexOf(u8, output, "[data-pale-fire-theme=\"full-black\"]").?, "--pf-background: #000000;") != null);
}
